env = WLR_NO_HARDWARE_CURSORS,1
env = LIBVA_DRIVER_NAME,nvidia

# 应用快捷键
bind = SUPER, Return, exec, alacritty
bind = SUPER, SPACE, exec, hyprlauncher
bind = SUPER SHIFT, M, exit
bind = SUPER, M, fullscreen, 0

# 窗口焦点切换（方向键）
bind = SUPER, left, movefocus, l
bind = SUPER, right, movefocus, r
bind = SUPER, up, movefocus, u
bind = SUPER, down, movefocus, d

bind = SUPER, 1, workspace, 1
bind = SUPER, 2, workspace, 2
bind = SUPER, 3, workspace, 3
bind = SUPER, 4, workspace, 4
bind = SUPER, 5, workspace, 5
bind = SUPER, 6, workspace, 6
bind = SUPER, 7, workspace, 7
bind = SUPER, 8, workspace, 8
bind = SUPER, 9, workspace, 9
bind = SUPER, 0, workspace, 0
# 移动窗口到指定工作区（0 对应工作区 10）
bind = SUPER SHIFT, 1, movetoworkspace, 1
bind = SUPER SHIFT, 2, movetoworkspace, 2
bind = SUPER SHIFT, 3, movetoworkspace, 3
bind = SUPER SHIFT, 4, movetoworkspace, 4
bind = SUPER SHIFT, 5, movetoworkspace, 5
bind = SUPER SHIFT, 6, movetoworkspace, 6
bind = SUPER SHIFT, 7, movetoworkspace, 7
bind = SUPER SHIFT, 8, movetoworkspace, 8
bind = SUPER SHIFT, 9, movetoworkspace, 9
bind = SUPER SHIFT, 0, movetoworkspace, 10
# move to left/right workspace
bind = CTRL+ALT, left, workspace, previous
bind = CTRL+ALT, right, workspace, next
# 使用 horizontal 替代 left/right
gesture = 4, horizontal, workspace
gestures {
    workspace_swipe_distance = 400       # 调低触发距离，让系统对你的滑动更敏感
    workspace_swipe_cancel_ratio = 0.2   # 调低取消比例，滑动不易被系统判定为“取消”
}
#igesture = 4, left, workspace, prev
#gesture = 4, left, workspace, next, invert 
#gesture = 4, right, workspace, next

# 使用 intel_backlight 设备控制亮度
bind = , XF86MonBrightnessUp, exec, brightnessctl -d intel_backlight set +5%
bind = , XF86MonBrightnessDown, exec, brightnessctl -d intel_backlight set 5%-

# close window
# 关闭窗口
bind = ALT, F4, killactive
bind = CTRL, W, killactive

# 显示器设置
monitor = eDP-2,3840x2160@120,0x0,1

# 输入设置
input {
    kb_options = caps:swapescape
    touchpad {
        natural_scroll = true
    }
}

exec-once = waybar &
exec-once = udiskie &
